server:
  port: 8383
spring:
  application:
    name: gateway-service
  cloud:
    consul:
      discovery:
        instance-id: ${spring.application.name}.${random.value}
#eureka:
#  client:
 #   serviceUrl:
  #    defaultZone: http://localhost:8761/eureka

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 300000
